language: cpp
compiler:
  - clang
  - gcc

before_install:
    # Add software package repository, containing updated build toochain, i.e. GNU GCC 4.8
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:kalakris/cmake --yes
  - sudo apt-get update -qq
    # Download boost 1.55 and extract the source archive
  - wget --no-verbose --output-document=boost_1_55_0.tar.bz2 http://sourceforge.net/projects/boost/files/boost/1.55.0/boost_1_55_0.tar.bz2/download
  - export BOOST_ROOT="$TRAVIS_BUILD_DIR/../boost"
  - export CMAKE_MODULE_PATH="$BOOST_ROOT"
  - mkdir -p $BOOST_ROOT
  - tar jxf boost_1_55_0.tar.bz2 --strip-components=1 -C $BOOST_ROOT

install: 
    # Install GNU GCC 4.8 required by use of C++11
  - sudo apt-get install -qq g++-4.8 gcc-4.8 libssl-dev cmake
  - export CXX="g++-4.8" CC="gcc-4.8"
    # Build boost libraries required by ledger
  - (cd $BOOST_ROOT; ./bootstrap.sh --with-libraries=atomic,chrono,context,coroutine,iostreams,system,thread)
  - (cd $BOOST_ROOT; ./b2 threading=multi --prefix=$BOOST_ROOT -d0 install)

script: mkdir build && cd build && cmake ../ && make